### ISSUE TITLE
[Request]: sidebar collapsed

### ISSUE THREAD

**Issue by raffistef** [grafana/grafana-iot-twinmaker-app#108]
It will be very useful to add an option for the scene viewer to load the panel with the sidebar collapsed.
Indeed, if the scene viewer is in a dashboard with other panels on the right, then the sidebar reduces to much the 3D scene.

**Comment by johnnyw-aws** [comment]
Hi @raffistef, configuration options for scene viewer aren't supported yet but we will take this feedback into consideration, thanks!

**Comment by raffistef** [comment]
Hi @johnnyw-aws thank you for your answer.
Please, do not hesitate to contact me if you need more feedbacks for this request!

**Comment by mukeshsahay** [comment]
@mumanity This is related to the sidebar enhancement you are working on. Please update this ticket once done.

**Comment by mukeshsahay** [comment]
Supported in v1.6.2
