### ISSUE TITLE
[Request]: Angle and zoom level predefined

### ISSUE THREAD

**Issue by raffistef** [grafana/grafana-iot-twinmaker-app#109]
It would be very great to be able to load the 3D view with a predined angle and zoom level defined by a variable in grafana.

**Comment by hwandersman** [comment]
There are new features coming Nov 17th that will allow you to define multiple camera views in a scene and select one as the default in a Grafana SceneViewer panel.

**Comment by raffistef** [comment]
Thank you for your answer. It will be the release v1.2.2?

**Comment by hwandersman** [comment]
This is in the 1.3.0 release. We support predefining cameras: https://docs.aws.amazon.com/iot-twinmaker/latest/guide/scenes-camera.html

You can set a default camera in the settings of the Scene Panel via a template variable with the name of the camera you defined in your scene.

**Comment by raffistef** [comment]
Thank you for your answer.

I am trying to set a default camera in the settings of the Scene Panel via a template variable but it doesn't load the view with a specific camera.

By the way, as you can see on my screenshots, in the entity variable name configuration, I can see the value of the variables
![entity_variable](https://user-images.githubusercontent.com/81618154/210252337-8c3d1a25-aa5e-415c-a9dd-6bb7b1bee427.png)
But in the active camera variable name configuration, I cannot see the value of the variables!
![action_camera](https://user-images.githubusercontent.com/81618154/210251321-03136666-76a8-4a6f-ab55-595ff0e18819.png)

I am pretty sure that it worked in the previous version of the pluging (v1.2.1).
Io you know if there is a bug from the v1.3.0 or I am wrong in the configuration?

Best regards,
