### ISSUE TITLE
[Request]: Twinamaker GetPropertyValue changes with latest AWS GO SDK

### ISSUE THREAD

**Issue by divya-sea** [grafana/grafana-iot-twinmaker-app#116]
Hi Team,

@toddtreece @ryantxu 
As per our discussion in the afternoon with Twinmaker team, I have pushed the latest AWS SDK GO to remote branch `athena-grafana`. And also I sent the requirement in the slack channel.

**Comment by toddtreece** [comment]
@divya-sea it looks like that branch is even with `main`:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/360020/199361956-c855ae2f-501e-443e-b793-b8fbe754479a.png">

**Comment by divya-sea** [comment]
Could you please check again.

**Comment by hwandersman** [comment]
Completed with this commit: https://github.com/grafana/grafana-iot-twinmaker-app/commit/7a095202a610b31c73d1217eedfee5e2122e3527
