### ISSUE TITLE
GetPropertyValueHistory by Entity filter is broken 

### ISSUE THREAD

**Issue by toddtreece** [grafana/grafana-iot-twinmaker-app#131]
Reported by @divya-sea:
1. Select queryType as GetPropertyValueHistory
2. Select entity
3. Select properties
4. Add filters
5. Filters are not working for any conditions.
    1. Code links - https://github.com/grafana/grafana-iot-twinmaker-app/blob/11172022_Release/src/datasource/components/QueryEditor.tsx#L568
    2. https://github.com/grafana/grafana-iot-twinmaker-app/blob/11172022_Release/src/datasource/components/QueryEditor.tsx#L491
    3. https://github.com/grafana/grafana-iot-twinmaker-app/blob/11172022_Release/src/datasource/components/FilterQueryEditor.tsx#L34
    
<img width="763" alt="image" src="https://user-images.githubusercontent.com/360020/201839876-c417f26a-cbc0-491d-9f47-f41d7534ce5a.png">

**Comment by hwandersman** [comment]
Fixed with this commit: https://github.com/grafana/grafana-iot-twinmaker-app/commit/3bde227747d8d67fe53be33566d1bd9a0c1209b8
