### ISSUE TITLE
Error with credentials - any suggestions?

### ISSUE THREAD

**Issue by IsmaRojo** [grafana/grafana-iot-twinmaker-app#15]
Error
{"message": "NoCredentialProviders: no valid providers in chain caused by: EnvAccessKeyNotFound: failed to find credentials in the environment. SharedCredsLoad: failed to load profile, . EC2RoleRequestError: no EC2 instance role found caused by: RequestError: send request failed caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}

**Comment by atifali** [comment]
@IsmaRojo what credentials are you using? looks like it cannot find any credentials in your environment - can you share some details on your setup?

**Comment by IsmaRojo** [comment]
hi @atifali 
thanks for your help


![grafana Twinmaker](https://user-images.githubusercontent.com/66044519/154153721-13f0c3a6-9a8a-439e-b65a-9f6305092411.JPG)

**Comment by IsmaRojo** [comment]
![image](https://user-images.githubusercontent.com/66044519/154163474-69eddfed-4e22-425d-968a-904240c90e46.png)
