### ISSUE TITLE
Chore: Remove or fix non-working main dashboard in play.grafana.org

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana-iot-twinmaker-app#151]
The [main dashboard](https://play.grafana.org/d/TRA53ITVz/main-dashboard) on play.grafana doesn't work, so it should be either fixed or removed.

- [x] Fix play.grafana.org Main Dashboard. Or delete it.
- [ ] Fix Main Dashboard in Sample Dashboards. Or delete it. May be nice to include a text box linking to the doc for how to set it up.

**Comment by fridgepoet** [comment]
I've requested some assistance in getting permissions to edit the dashboard. https://raintank-corp.slack.com/archives/C01U0V9T8MR/p1675767767697449

Here's what can be done to improve the errors in this dashboard:
- [ ] Set a default for display_entity to Mixer_0_cd81d9fd-3f74-437a-802b-9747ff240837 (same default for sel_entity on the Mixer Alarm Dashboard)
- [ ] Edit panel "Selected Alarm History", choose Component Name = AlarmComponent
- [ ] Edit panel "Scene Viewer", open Panel options (to the right). Under "AWS IoT TwinMaker Scene Viewer", choose CookieFactory.
In the Query Editor: Under Component Type, select  "com.example.cookiefactory.alarm". Under Filter, set the value = "ACTIVE".
Add a query. Get Property Value History by Entity. Entity WaterTank, component WaterTank, property flowRate1.
Add another query. Get Property Value History by Entity. Entity Mixer_1, component MixerComponent, property Temperature.
(Not sure if these queries are essential, this is copying from Mixer Alarm Dashboard).

- [ ] Go to Main Dashboard/Settings > Variables. Add a new variable. Type: Text box. Name: kvs_stream_name. Default value: cookiefactory_mixerroom_camera_02 
Show on dashboard: Nothing
(this is the same as in Mixer Alarm Dashboard)
Go back to the dashboard. Edit "Video Player" panel. Open Panel options (to the right). Under "AWS IoT TwinMaker Video Player" > Kinesis video stream name, select template variable ${kvs_stream_name}.
Under Entity, choose ${sel_video_entity}
Under Component Name, choose ${sel_video_comp}

- [ ] Edit panel "Selected Time Series History"
In Query Editor, select Entity ${display_entity}
Under Selected Properties, choose RPM
(I cannot get multiple properties to display from one query, so the following is a workaround to get Temperature)
Duplicate the above query. Change Selected Properties to Temperature.

**Comment by iwysiu** [comment]
Nice! Though I'm wondering: does this dashboard fixed up demonstrate anything that we don't already have in the Mixer Alarm Dashboard? Because if it doesn't, I'm inclined to just remove it. (also if I'm understanding the board correctly, I think `display_entity` can just be removed and replaced with `sel_entity` in queries)

**Comment by fridgepoet** [comment]
@iwysiu Can you clarify what you would like done for this ticket? Just want to know if you want the demo Main Dashboard to be removed or fixed. And if you want the importable sample Main Dashboard to be removed or fixed.

I have some ongoing work in progress to improve the importable sample Main Dashboard in the repo. If we do decide to continue the work to fix that, I think ultimately play.grafana.org can reflect what is possible using the imported Main Dashboard.
