### ISSUE TITLE
Chore: Handover to AWS Plugins

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana-iot-twinmaker-app#153]
Add basic templates and processes:

- [x] - CODEOWNERS
- [x] - Bugs
- [x] - FR (to Discussions)
- [x] - PR template
- [x] - Automate CHANGELOG
- [x] - Levitate (as comments)
- [x] - Add to project board (for the new squad)

This does not include: Code coverage

- [x] Before closing this issue, we should test them out.

**Comment by fridgepoet** [comment]
I am not aware of any of our other repos which have automated changelogs besides main Grafana. 
It seems possible, but require labels and milestones and eventually implementing the labels/milestones requirements for merging. I think that could be an interesting feature to add, but maybe a little too much for this handover task.

Also I think none of our other repos have PR templates. I've added one here which I think could be nice to add to our other repos.
