### ISSUE TITLE
Improvement: ConfigEditor should be clearer about workspace loading

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana-iot-twinmaker-app#154]
Currently, when you create a new TwinMaker datasource, the workspace field is somewhat confusing. As a user, you fill in the Authentication, Assume Role, and Workspace Id fields, and after saving it, the Workspace ID field swaps from a text field to a select and says that the Workspace ID isn't found:

![Screen Shot 2023-01-27 at 2 14 37 PM](https://user-images.githubusercontent.com/5421859/215176301-2e3eeea4-7941-46c4-a722-5d7dd32bd7d0.png)

If you save again, it will load in the workspaces and remove the `(not found)` part of the message, but this could be confusing for users.

Instead, it should work like the Cloudwatch Logs Config Editor, which tells the user to save the datasource first, and then they can select from the loaded values.
![Screen Shot 2023-01-27 at 2 01 19 PM](https://user-images.githubusercontent.com/5421859/215177171-7bac41b1-d5ec-41c2-88f8-8cd43fa8c990.png)

**Comment by taleena** [comment]
AWS agreed this would be a valuable improvement.
