### ISSUE TITLE
Fix "Validation error" message when Assume Role ARN is misconfigured

### ISSUE THREAD

**Issue by hwandersman** [grafana/grafana-iot-twinmaker-app#18]
Need a better error message shown when the Assume Role ARN does not work for a TwinMaker datasource. The error usually occurs when the auth provider creds doesn't have access to the assume role ARN. If any of those fields are incorrect the error message is not clear, so we need to surface the correct one.

**Comment by atifali** [comment]
this currently looks like this:

for example when there is a faulty assume role ARN:
<img width="754" alt="Screen Shot 2022-02-14 at 6 18 00 PM" src="https://user-images.githubusercontent.com/12394084/153979987-85e058f1-c030-4a94-9833-d38237de036b.png">
