### ISSUE TITLE
Error when loading scene - Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by mukeshsahay** [grafana/grafana-iot-twinmaker-app#203]
**What happened**:
Getting the following error when loading a scene in the Grafana dashboard:
**Failed to construct 'URL': Invalid URL**

![image (1)](https://github.com/grafana/grafana-iot-twinmaker-app/assets/43108986/f1c5953c-fe0f-427d-805d-928449f4f6f9)

**What you expected to happen**:
Scene should get loaded correctly, without any issue.

**How to reproduce it (as minimally and precisely as possible)**:
This issue is observed when the Endpoint is blank in the datasource. However, it is not always reproducible.

**Anything else we need to know?**: 
This issue is fixed if we explicitly provide the Endpoint in the datasource.

Console logs:
![image](https://github.com/grafana/grafana-iot-twinmaker-app/assets/43108986/87954984-10f8-42f5-9d5b-93016043615f)

**Environment**:
- Grafana version: v8 and v9
- Plugin version: 1.6.2

**Comment by mukeshsahay** [comment]
<img width="763" alt="Screenshot 2023-07-18 at 11 09 06 AM" src="https://github.com/grafana/grafana-iot-twinmaker-app/assets/43108986/c99d687d-d1df-49af-bdbb-39e3c94c3210">

**Comment by taleena** [comment]
This is sometimes experienced when loading a scene or saving a datasource. If a datasource is saved like this, it will always occur. To specifically define the Endpoint is optional, and is sometimes calculated via on other settings within the datasource (AWS region, etc), but this may fail to happen successfully.

**Comment by katebrenner** [comment]
Hey Mukesh - I'm not seeing this error upon having blank endpoint. Would you mind either adding some more detail to the steps to reproduce or providing a screen recording of the error occurring? Thanks!

**Comment by katebrenner** [comment]
aha! thanks Mukesh - I am able to reproduce and I see the error now
