### ISSUE TITLE
Upgrade plugin dependencies to React 18

### ISSUE THREAD

**Issue by idastambuk** [grafana/grafana-iot-twinmaker-app#205]
As of Grafana10, Twinmaker runs in Grafana's React18 environment, so we should update React dev dependencies to 18 as well. 
Additionally, iot-app-kit with SceneViewer and VideoPlayer plugins have been upgraded to React18, so we should do this before we bump the versions. 

The [Grafana React 18 PR description](https://github.com/grafana/grafana/pull/64428) could be useful to see what needs to be upgraded

**Comment by katebrenner** [comment]
goal to have this by Aug 15

**Comment by idastambuk** [comment]
Right now, we're waiting for AWS components to be updated, so moving to Waiting
