### ISSUE TITLE
Error when first loading dashboard page: Cannot read properties of undefined (reading 'TextHighlightRules')

### ISSUE THREAD

**Issue by hwandersman** [grafana/grafana-iot-twinmaker-app#221]
**What happened**:
![image](https://github.com/grafana/grafana-iot-twinmaker-app/assets/87385528/cea4dd56-ec5a-4e9c-b67a-3ff77ec083e5)

This error appears whenever the Grafana dashboard page first loads. All datasources are broken. On a page refresh this error goes away and things work as expected.

**What you expected to happen**:
This error should not pop up and the TwinMaker datasources should work properly on the first load of the page.

**How to reproduce it (as minimally and precisely as possible)**:
I am unable to produce from the dev team. This is happening with a customer's Grafana self-managed server.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.5.2
- Plugin version: 1.7.1

**Comment by MO-Elmu** [comment]
Any update ?

**Comment by idastambuk** [comment]
We're waiting for more info in order to be able to reproduce this. Will update when we know more.

**Comment by sarahzinger** [comment]
@hwandersman is this issue still happening for your customer? Do we have repro steps for this one yet? If not maybe we can close as stale

**Comment by sarahzinger** [comment]
Closing as stale

**Comment by taleena** [comment]
Likely resolved on TM side.
