### ISSUE TITLE
Scrollability behavior changed (scrolling is disabled) within Panel in Grafana 10

### ISSUE THREAD

**Issue by MO-Elmu** [grafana/grafana-iot-twinmaker-app#224]
**What happened**:
we used to be able to have scroll bar with in our query editor panel when i test in Grafana 8.4.7 and 9.4.1 . Now when I test with our plugin in 10.1.1 I see scrolling only on the dashboard level and no scrolling within the panel.

**What you expected to happen**:
Scrolling to be enabled by default within Panel.

**How to reproduce it (as minimally and precisely as possible)**:
Inside our AWS IoT TwinMaker plugin start a dashboard and add a new AWS IoT TwinMaker Query Editor panel and try to scroll inside the panel. You can scroll in all grafana versions except grafana 10. 

**Anything else we need to know?**:
Attached 3 videos showing the behavior in AMG grafana 8.4 and local grafana 9.4 (expected behavior) and in grafana 10.1.1 (buggy behavior ).
Also there is a successfully tested workaround suggested by @kevinwcyu that will restore panel scrollability which is disabling newPanelChromeUI feature toggle in grafana.ini (newPanelChromeUI = false).

**Environment**:
- Grafana version:
- 10.1.1
- Plugin version:
- 1.7.1 or any version the behavior is the [same.]

https://github.com/grafana/grafana-iot-twinmaker-app/assets/20994167/bdd79354-7f95-49f6-9459-6596f46049ee

https://github.com/grafana/grafana-iot-twinmaker-app/assets/20994167/d5319754-e3e7-4309-bb60-6fe4636bf27a

https://github.com/grafana/grafana-iot-twinmaker-app/assets/20994167/0c6939da-edf1-459b-924f-baf668977f3e

**Comment by idastambuk** [comment]
It looks like this is a problem with dashboards. We've contacted the relevant team and submitted a bug report, follow here: https://github.com/grafana/grafana/issues/75422
