### ISSUE TITLE
GetAlarms API Update for Large Data Set

### ISSUE THREAD

**Issue by YusakuNo1** [grafana/grafana-iot-twinmaker-app#24]
**Background**
With the current approach, since Grafana need to loop through all the entities in TwinMaker, which may not be able to scale for large systems (e.g. with 100K entities). This is the update to resolve the issue.

**Current Workflow**
Steps

1. (Result is cached) Call API ListComponentTypes to get all component types which extend from the basic alarm component type "com.amazon.iottwinmaker.alarm.basic"
2. (Result is cached) Call API ListEntities with all the component types from the last step.
3. (Result is cached) Call API GetEntity for all the entities from the last step to get the entity detailed information (includes componentName).
4. Build a HashMap for externalID->entityId/componentName lookup
5. Call API GetPropertyValueHistory for all the componentTypes from step 1, and then use the externalIDs from API response with the HashMap from step 4 to add entityId/componentName into the response.

Traffic Estimation: for a customer with 100K entities, 10 alarm components and 20 active alarms, the number of API calls are: 100,000 + 10 * 2 + 1

**New workflow**

Steps

1. (Result is cached) Call API ListComponentTypes to get all component types which extend from the basic alarm component type "com.amazon.iottwinmaker.alarm.basic"
2. Call API GetPropertyValueHistory for all the componentTypes from step 1
3. For each data frame, search in-memory cache for the externalID, if exists, use cache to add entityId/componentName into the response, otherwise:
    3.1 Call API listEntities with externalID as filter to find the entity summary.
    3.2. Call API GetEntity with the entityID from step 3.1 to find the entity componentName.

Traffic Estimation: for a customer with 100K entities, 10 alarm components and 20 active alarms, the number of API calls are: 20 + 20 + 10 + 1

**Comment by sheilaXu** [comment]
@atifali From the last conversation, we want to combine the implementation of GetComponentHistory and GetAlarm queries. They will still be two separate options in the query type selection, but should have the same logic to get data.

For the data frame returned from GetComponentHistory, it should have the same field as current, but have the "entityId" and "componentName" in labels.

For GetAlarms, we can still have the same format as current, but make sure it has the values of entityId, componentName, status and time returned. then I can grab those values in scene viewer to convert to the data frame I need.

**Comment by hwandersman** [comment]
Highest priority
