### ISSUE TITLE
Multi-languages support

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana-iot-twinmaker-app#246]
### Discussed in https://github.com/grafana/grafana-iot-twinmaker-app/discussions/210

<div type='discussions-op-text'>

<sup>Originally posted by **raffistef** August 23, 2023</sup>
Hello,

Thanks to the new feature of AWS Managed Grafana, I am now using Grafana v9.6 which supports language preferences.
Thus I have configured "french" as default language of my Grafana...
But in my dashboards, I still see the Twinmaker panel in english "hiercharchy", "settings".
Do you know if a multi-languages support (if possible with french) is in your roadmap?

Thank you,</div>

**Comment by katebrenner** [comment]
This is a great idea, we will look into getting this onto Grafana's roadmap, but closing the issue since we will not be implementing this in the near future.
