### ISSUE TITLE
Get selected entity

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana-iot-twinmaker-app#247]
### Discussed in https://github.com/grafana/grafana-iot-twinmaker-app/discussions/195

<div type='discussions-op-text'>

<sup>Originally posted by **raffistef** May 31, 2023</sup>
Hello,

Thanks to the option "customSelCompVarName" of the scene viewer plugin Grafana, we are able to know which tag the user clicks on (through a Grafana variable). But when the user clicks on a 3D object, the variable "customSelCompVarName" is not updated whereas we can see in the hierachy list of the plugin that the 3D object has been selected (thanks to a blue point). So is it possible in Grafana to use a variable to store which 3D object the user clicks on?

Thank you</div>

**Comment by taleena** [comment]
Feedback from TM team: would need more information about what information from the 3D object you'd want to store, and explain in more detail about the use case you are trying to address. How would this help you do what you want to do?

For now, we will close as "not planned".
