### ISSUE TITLE
Video Player Connector SiteWise

### ISSUE THREAD

**Issue by nesvieraquetocos** [grafana/grafana-iot-twinmaker-app#26]
![image](https://user-images.githubusercontent.com/66044519/155930051-2525291f-c95c-4ce2-b3ea-797c49777b09.png)

![image](https://user-images.githubusercontent.com/66044519/155929743-52c8f7e6-af5e-498d-bd6a-2026aa5309b6.png)
![image](https://user-images.githubusercontent.com/66044519/155929795-c0ceddfb-655d-4fd5-aa8b-cabfec790bcb.png)

**Comment by IsmaRojo** [comment]
I still can't solve this issu, could you help me, thanks.

**Comment by IsmaRojo** [comment]
@atifali  Hi! Could you help me with this, is there any documentation to follow? Thank you

pD:I hope not to bother with the mention

**Comment by hwandersman** [comment]
Hi, here is our documentation for this panel: https://github.com/grafana/grafana-iot-twinmaker-app/blob/main/src/panels/video-player/README.md

I'll need more information about your setup (workspace, entities, panel config)

**Comment by mukeshsahay** [comment]
Closing this as not updates to this ticket for a few months now. Also, verified that this is working fine.
