### ISSUE TITLE
Amazon Managed Grafana:  IOT Twinmaker plugin can't query 3D data (Windmills)

### ISSUE THREAD

**Issue by foleng1** [grafana/grafana-iot-twinmaker-app#270]
**What happened**:
can't visualize windmills in 3D

getting the below error;

Error: ConnectorFailureException: Received following error when calling SiteWise: Failed to invoke SiteWise API - GetAssetPropertyValueHistory. siteWiseAssetId: <> , siteWisePropertyId: <>

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: AMG Grafana 9.4
- Plugin version: IoT TwinMaker 1.11.1

**Comment by kevinwcyu** [comment]
Hi @foleng1, Just wanted to get some more information before we can investigate this

- Can you provide a minimal set of reproduction instructions?
  - Additionally if you can provide a screen recording/screenshot of the issue in action that would also be useful
- Did this work before in a previous TwinMaker version, and stopped working now?

**Comment by sarahzinger** [comment]
Closing as stale
