### ISSUE TITLE
Extra empty blue banner is showing for SceneViewer with matterport scene

### ISSUE THREAD

**Issue by sheilaXu** [grafana/grafana-iot-twinmaker-app#274]
**What happened**:
When loading a matterport scene in Grafana v10, there will be an extra empty blue banner showing up that is not interact-able. The same scene will not have the blue banner when using Grafana v9, and non-matterport scene is not having the blue banner in v10

<img width="841" alt="Screenshot 2024-02-15 at 5 31 31 PM" src="https://github.com/grafana/grafana-iot-twinmaker-app/assets/9315598/611a020c-e36d-40fc-bba0-539ad810f601">

**What you expected to happen**:
There should be no blue banner.

**How to reproduce it (as minimally and precisely as possible)**:
With Grafana v10, load a matterport scene in SceneViewer panel

**Anything else we need to know?**:
From console log, there is a failed matterport API call. But since the scene is loading fine, if it's causing the blue banner, then we want to remove it for this case.

**Environment**:
- Grafana version: 10.2.3
- Plugin version: 1.11.0

**Comment by sarahzinger** [comment]
Reaching out to the TwinMaker team at AWS to see their thoughts on this

**Comment by torkelo** [comment]
@sheilaXu is this on Grafana Cloud? Looks like the cloud trial / licence banner 

What is SceneViewer?

**Comment by sarahzinger** [comment]
SceneViewer is a panel visualization that comes installed with the twinmaker datasource/app.

**Comment by sarahzinger** [comment]
I'm a bit stumped but my current hunch is that there is some kind of style change here that is causing unexpected style changes in Twinmaker's Scene Viewer Panel. 

The Blue Bar itself is coming from within the matterport-viewer webcomponent which I don't believe grafana has any direct control over:
![Image](https://github.com/grafana/grafana-iot-twinmaker-app/assets/6620164/7b182271-eb12-4db3-b02b-ab0f829c2544)

What's interesting is that this "error-bar" component exists in the dom in earlier versions of grafana as well it's just invisible:
![Image](https://github.com/grafana/grafana-iot-twinmaker-app/assets/6620164/a199bc38-30d7-49cb-b782-84507391af79)

Is it possible for the Twin Maker team to edit the css in the Matterport Web component?

**Comment by mitchlee-amzn** [comment]
This blue bar is coming from Matterport, the likely fix is to upgrade the Matterport SDK Version, update the IotAppKit version in the Grafana Plugin, and see. Otherwise, I can reach out to our contacts at Matterport to get some next steps.

**Comment by taleena** [comment]
Update that TM team may have a fix in for this and is awaiting testing feedback from customer, then we can close this out.

**Comment by taleena** [comment]
TM team mentioned we can close this out, customer verified. Thank you!
