### ISSUE TITLE
Restore original dashboard after a dashboard merge

### ISSUE THREAD

**Issue by hwandersman** [grafana/grafana-iot-twinmaker-app#3]
When a dashboard is merged many of the panels are replaced. A user should be able to click the back button on their browser to restore the previous state of the dashboard. If the dashboard is merged multiple times, the history should be maintained.

Possible solutions:

* Store the dashboardId to merge in a template variable - when it is empty the original dashboard is restored
* When all rules are not matched on the Dashboard Layout panel the original dashboard is restored
* Have a refresh button on the Dashboard Layout panel that forces the dashboard back to its original state

**Comment by taleena** [comment]
Talked about this with the TM team, it's a larger, broader request for handling overall dashboard state. If it comes up again in the future, it would need to be filed with a different team, so closing here.
