### ISSUE TITLE
Update GoLang SDK

### ISSUE THREAD

**Issue by hwandersman** [grafana/grafana-iot-twinmaker-app#30]
Use new GoLang SDK for TwinMaker. 

Need to make the following changes to our backend plugin:
* PropertyValue.Timestamp is now PropertyValue.Time
* The timestamp is now represented in ISO 8601 format - test that passing this to panels doesn't break anything

**Comment by mukeshsahay** [comment]
https://github.com/grafana/grafana-iot-twinmaker-app/pull/43

**Comment by mukeshsahay** [comment]
Updated the AWS GoLang SDK to latest version 1.44.1.
