### ISSUE TITLE
Handle ISO 8601 Timestamp in GoLang

### ISSUE THREAD

**Issue by hwandersman** [grafana/grafana-iot-twinmaker-app#46]
Our GetPropertyValueHistory API has deprecated the "Timestamp" field in the response and "StartDateTime" and "EndDateTime" in the request. We are being pushed to use the "Time" field in the response and "StartTime" and "EndTime" in the request. These new fields use timestamps as a string object.

In GoLang we use the RFC3339 [constant](https://pkg.go.dev/time#pkg-constants) to format strings and timestamps. This is strictly matches the format "YYYY-MM-DDTHH:MM:SSZ". However, the API response only promises the ISO 8601 format where the seconds are optional. We need to handle the case where seconds are missing and format timestamps correctly.

Example values in a response:
```
                {
                    "value": {
                        "stringValue": "ACTIVE"
                    },
                    "time": "2022-04-27T17:50Z"
                }

vs


                {
                    "value": {
                        "stringValue": "ACTIVE"
                    },
                    "time": "2022-04-27T17:49:46Z"
                }
```
2022-04-27T17:50Z is missing seconds so converting this directly with the RFC3339 format will result in a timestamp that equates to 0. Need to add the ":00" before the "Z" to ensure a correct conversioin.

**Comment by hwandersman** [comment]
Example formats we need to validate:

Representation	                                  Sample string
Seconds precision	                                  2017-11-15T11:18:42Z
Seconds precision with ZoneOffset	2017-11-15T11:18:42+08:00
MilliSeconds precision	                         2017-11-15T11:18:42.573Z
MicroSeconds precision:	                 2017-11-15T11:18:42.573001Z
NanoSeconds precision	                         2017-11-15T11:18:42.573000001Z
NanoSeconds precision with Zone	2017-11-15T11:18:42.573000001+08:00
Seconds truncated                                  2022-04-27T17:50Z  or 2022-04-27T17:50+12:00

**Comment by mukeshsahay** [comment]
Fixed: https://github.com/grafana/grafana-iot-twinmaker-app/pull/50

**Comment by mukeshsahay** [comment]
Fixed: https://github.com/grafana/grafana-iot-twinmaker-app/pull/50
