### ISSUE TITLE
Integrate with new Grafana 8.5 feature: Table pagination

### ISSUE THREAD

**Issue by hwandersman** [grafana/grafana-iot-twinmaker-app#48]
The GetPropertyValueHistory API returns paginated results, but we haven't been able to separate these pages visually on the dashboard. Onboard to the new Table pagination and ensure customers can see 1 page of responses at a time.

**Comment by lean257** [comment]
Given that this would require new feature development in core, I filed a [request](https://github.com/grafana/grafana/discussions/50047) in our core repo.
