### ISSUE TITLE
Url link is misconfigured on table panel

### ISSUE THREAD

**Issue by hwandersman** [grafana/grafana-iot-twinmaker-app#52]
When clicking on a URL in the table panel it does not open that URL, but it is treated as a relative URL appended to the base path.

Need to fix the following: https://github.com/grafana/grafana-iot-twinmaker-app/blob/3917e1de0187ee72e1585412d2e330cf5c635766/pkg/plugin/twinmaker/utils.go#L133

<img width="1439" alt="Screen Shot 2022-05-16 at 2 08 40 PM" src="https://user-images.githubusercontent.com/87385528/168656017-10506397-3543-4815-a707-c710f72b858f.png">
<img width="1440" alt="Screen Shot 2022-05-16 at 2 08 52 PM" src="https://user-images.githubusercontent.com/87385528/168655928-895e4afa-94d2-4a9b-8e50-8716e1b85d89.png">
85528/168655920-78cea18d-0611-4ff4-8856-563ae19bd042.png">

**Comment by lean257** [comment]
Hm these links seem to correctly redirect for me. Can you or someone on your team double check in case i'm the outlier? 
![screen-recorder-wed-may-18-2022-13-51-33](https://user-images.githubusercontent.com/17167829/169109506-dad75896-483c-43c9-b3b7-053a7612b9ec.gif)
