### ISSUE TITLE
GetAlarms query missing data

### ISSUE THREAD

**Issue by sheilaXu** [grafana/grafana-iot-twinmaker-app#58]
Refreshing the getAlarms query will return different number of alarms, and some alarms will be missing

**Comment by sheilaXu** [comment]
https://user-images.githubusercontent.com/9315598/169608579-49e5ab61-1456-4264-a690-1d36ddb8dda1.mov

**Comment by lean257** [comment]
I'm not able to reproduce this currently, can you share your settings (what kind of OS, browser, etc.)? Does this happen on dev or on play site? Can you check if it's happening for you on play?
