### ISSUE TITLE
cache time series data and append new data on refresh

### ISSUE THREAD

**Issue by lean257** [grafana/grafana-iot-twinmaker-app#64]
Should mirror the behavior of sitewise

**Comment by hwandersman** [comment]
Update: we would be satisfied with a streaming plugin implemented for our datasource. Need the ["Stream" functions](https://github.com/grafana/grafana-starter-datasource-backend/blob/main/pkg/plugin/plugin.go#L133-L194) implemented for GetPropertyValueHistory.

The GetPropertyValueHistory API takes a start time, end time, and the property path (entityId/componentName/propertyName/componentType).

So let’s say the time range is [now - 10m, now], the refresh rate is 1m, and now = 12:00.

First call:
GetHistory for [11:50, 12:00] --> get 100 datapoints (10 datapoints per minute)
Second call:
GetHistory for [12:00, 12:01] --> get 10 datapoints
etc.
So the “polling” loop just keeps track of the last end time and calls our API with a new time range set by the refresh rate.
