### ISSUE TITLE
Grafana/UI CustomScrollbar import broken and blocking builds

### ISSUE THREAD

**Issue by hwandersman** [grafana/grafana-iot-twinmaker-app#69]
There is an error in PR #68 build: https://drone.grafana.net/grafana/grafana-iot-twinmaker-app/162/1/5
```
Compiling...  ERROR in grafana-iot-twinmaker-app/src/panels/alarm/TwinMakerAlarmPanel.tsx(41,6):
  TS2322: Type '{ children: Element; autoHeightMin: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
    Property 'children' does not exist on type 'IntrinsicAttributes & Props'.
  ERROR in grafana-iot-twinmaker-app/src/panels/layout/LayoutPanel.tsx(231,12):
  TS2322: Type '{ children: Element; autoHeightMin: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
    Property 'children' does not exist on type 'IntrinsicAttributes & Props'.
✖ Build failed
error Command failed with exit code 1.
```

Issue with CustomScrollbar here: https://github.com/grafana/grafana-iot-twinmaker-app/blob/main/src/panels/alarm/TwinMakerAlarmPanel.tsx#L41
And in the LayoutPanel.

Need to fix this broken dependency.

**Comment by toddtreece** [comment]
fixed by updating the yarn.lock manually in https://github.com/grafana/grafana-iot-twinmaker-app/commit/403a0f5cb872cda866087016007abcf9e7048671
