### ISSUE TITLE
Non-time-series and non-component-type properties are not showing in Grafana query selection

### ISSUE THREAD

**Issue by YusakuNo1** [grafana/grafana-iot-twinmaker-app#9]
For properties are non-time-series, if they are not declared in component type, then the won't be shown in Grafana query.

For example, ```KinesisVideoStreamName``` and ```CaptureStartTime ``` are declared in SiteWatch as entity level of property, they are not showing in Grafana selection; on the other side, ```sitewiseAssetId``` and ```sitewiseAssetModelId``` are defined in component type level, they are shown in Grafana query. Double confirmed that all these 4 properties are in ```getEntity``` response.

**Comment by katebrenner** [comment]
We support GetpropertyValue API which lists non time series properties
