### ISSUE TITLE
[Bug - Critical] Live time series history streaming feature not working on AMG

### ISSUE THREAD

**Issue by mukeshsahay** [grafana/grafana-iot-twinmaker-app#95]
"Live time series history streaming" is a new feature supported in the TwinMaker plugin v1.2.0, but this is not working on the AMG setup.
User can enable the streaming and can set the streaming interval in the query editor. However, the panel is not updated with the latest data.

This is a critical issue and many of our customers are reporting this.

![image (2)](https://user-images.githubusercontent.com/43108986/188245047-9de0c548-dabd-4ef0-97ee-6c7097168d88.png)

**Comment by taleena** [comment]
Hello @mukeshsahay - given that this is happening within AMG, please escalate to that team. They have the ability to file a support escalation with us if it's discovered to be an issue with the plugin itself.

**Comment by ryantxu** [comment]
In https://github.com/grafana/grafana-iot-twinmaker-app/pull/97 we can remove the buttons, but getting streaming to work will be in the AMG side

**Comment by eercanayar** [comment]
This issue is affecting me currently. Is there any ETA for the fix?

**Comment by mukeshsahay** [comment]
Thank you @ryantxu and @toddtreece for removing the Streaming related controls from the UI if Grafana Live is disabled.
I confirm that the reason for streaming to not work on AMG is because "Grafana Live" is disabled on AMG. We will take this up with AMG.

Due to the new changes for streaming and dependency on Grafana Live, we observed another issue where the Grafana panels are not displaying complete dataset and is only showing 100 datapoints. As discussed, we will be adding a fallback solution when Grafana Live is disabled to work as it was working prior to adding the streaming feature.

**Comment by mukeshsahay** [comment]
<img width="1313" alt="Screen Shot 2022-09-28 at 9 37 55 PM" src="https://user-images.githubusercontent.com/43108986/192830470-4e538ca7-864c-47f9-8245-43e9ce18e38d.png">
